name: ai_chat_bot
description: "AI Chat Bot."

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  auto_route: ^10.0.1
  bloc_test: ^10.0.0
  flutter_bloc: ^9.1.1
  flutter_chat_types: ^3.6.2
  flutter_dotenv: ^5.2.1
  flutter_native_splash: ^2.4.6
  flutter_svg: ^2.0.10
  get_it: ^8.0.3
  gpt_markdown: ^1.0.19
  hive_ce: ^2.11.3
  http: ^1.4.0
  introduction_screen: ^3.1.17
  mocktail: ^1.0.4
  path_provider: ^2.1.1
  permission_handler: ^12.0.0+1
  speech_to_text: ^7.0.0
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  auto_route_generator: ^10.0.0
  build_runner: ^2.4.8
  flutter_launcher_icons: "^0.14.3"
  flutter_lints: ^5.0.0
  hive_ce_generator: ^1.9.2

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_icon.png"
  min_sdk_android: 16

flutter:
  uses-material-design: true
  generate: true

  assets:
    - .env
    - assets/images/chat_bot_logo.png
    - assets/images/chat_bot_small_logo.svg
    - assets/images/chat_bot_small_logo_inversed.svg
    - assets/images/tap_to_chat_icon.svg
    - assets/images/send_icon.svg

flutter_native_splash:
  color: "#131313"
  image: "assets/images/chat_bot_logo.png"
