name: ai_chat_bot
description: "AI Chat Bot."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_native_splash: ^2.4.6
  flutter_gemini: ^3.0.0
  flutter_chat_ui: ^2.1.3


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/chat_bot_logo.png

flutter_native_splash:
  color: "#131313"
  image: "assets/images/chat_bot_logo.png"
