// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:ai_chat_bot/data/models/hive_storage/hive_chat_message.dart';
import 'package:ai_chat_bot/data/models/hive_storage/hive_chat_session.dart';
import 'package:ai_chat_bot/data/models/hive_storage/hive_memory_item.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(HiveChatMessageAdapter());
    registerAdapter(HiveChatSessionAdapter());
    registerAdapter(HiveMemoryItemAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(HiveChatMessageAdapter());
    registerAdapter(HiveChatSessionAdapter());
    registerAdapter(HiveMemoryItemAdapter());
  }
}
